services:
  pricing-service:
    image: pricing-service:latest
    container_name: pricing-service
    restart: unless-stopped
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    command: sh ./entrypoint.sh
    networks:
      - pricing-service-network
networks:
  pricing-service-network:
    name: rule-service-network
    external: true
